In [3]:
# Hier nichts ändern!
import sys
sys.path.append("../code")
from setup_AB2 import *

<img src = "../figs/cammp.png" style="height:5em; width:auto" align="right">

# Netflix | Arbeitsblatt 2: Modell <i class="fa fa-sitemap" style="font-size:26px"></i>

Wir werden zunächst mit kleinen Beispieldatensätzen arbeiten und versuchen interessante Eigenschaften und Zusammenhänge in den Daten auszunutzen, um ein Empfehlungssystem zu entwickeln. Am Ende des Workshops werden wir das Empfehlungssystem  auf dem Netflixdatensatz testen!


## 1) Die Zerlegung der Rating-Tabelle


### Erstes Beispiel

Wir starten mit einem kleinen Beispiel, bei dem die folgenden sechs Filme von vier Nutzern bewertet wurden:
 
 $\cdot$ | Name des Films  |  $\cdot$ | Name des Films 
---|--- | ---|---       
 <i class="fa fa-film" style="font-size:22px"></i>$_1$ | Batman Returns   |  <i class="fa fa-film" style="font-size:22px"></i>$_4$ | Der Herr der Ringe: Die Rückkehr des Königs 
 <i class="fa fa-film" style="font-size:22px"></i>$_2$ | Spongebob Schwammkopf: Home Sweet Pineapple  |  <i class="fa fa-film" style="font-size:22px"></i>$_5$ | Miss Undercover (*Miss Congeniality*)
 <i class="fa fa-film" style="font-size:22px"></i>$_3$ | Die Simpson - Staffel 5  |  <i class="fa fa-film" style="font-size:22px"></i>$_6$ | The Fast and the Furious 1  


Wir starten mit einem Beispiel, bei dem alle Bewertungen bekannt sind. Die  Rating-Tabelle lautet:



<div style="text-align:center">
<img src="../figs/AB1_A2_a.png" width="400", class="center">
</div>




Wir unterscheiden die sechs Filme  bezogen auf zwei Genres: **Action (A) und Comedy (C).**   Dazu haben wir ungefähr  festgelegt, wie groß der Action- und Comedy-Anteil (von 1 = gering bis 5 = hoch) bei den sechs Filmen ist. Dies haben wir in der folgenden Movie-Tabelle $M$ zusammengefasst:  
       
    
<div style="text-align:center">
<img src="../figs/AB1_A2_a2.png" width="400", class="center">
</div>

**So kannst du die Tabelle lesen:**  
An der 6. Spalte kann man ablesen, dass der Film 6 (The Fast and the Furious 1) einen hohen Anteil an Action und einen geringen Anteil an Comedy hat.


____

<div id="exercise" class="alert alert-info">
    <h3><i class="fa fa-laptop" style="font-size:30px"></i> <br><br>a) Genres Zuordnen  </h3>
    Beurteile, ob die  User 1 bis 4 Action bzw. Comedy mögen oder nicht. Schaue dir dazu die Movie-Tabelle $M$ und die Rating-Tabelle $R$ genauer an. Ersetze  die  <strong>None</strong> im folgenden Code
    <ul>
        <li>durch eine <strong>1</strong> wenn der Nutzer das Genre mag  </li>
        <li>durch eine <strong>0</strong> wenn er das Genre nicht mag. </li>
    </ul>
Führe den Code aus, um dein Ergebnis überprüfen zu lassen. Klicke dazu in das Codefeld und drücke auf den  <img src="../figs/run.png" width="10"/> - Button.
</div>

In [ ]:
# User 1:
A1 = None; 
C1 = None; 

# User 2:
A2 = None; 
C2 = None; 

# User 3
A3 = None; 
C3 = None; 

# User 4:
A4 = None; 
C4 = None; 
checkPreferences(A1,C1,A2,C2,A3,C3,A4,C4)

<div id="information" class="alert alert-success">
    <h2><i class="fas fa-info" style="font-size:36px"></i> &nbsp;  Annahme</h2>
    Wir gehen davon aus, dass die Nutzer die  Genres <strong>Comedy</strong> bzw. <strong>Action</strong> stets komplett (=1) oder gar nicht (=0) mögen. Natürlich wäre es auch denkbar, dass ein Nutzer eine Kategorie nur <strong>teilweise</strong> mag. Dies werden wir im Verlauf des Workshops berücksichtigen. 
</div>

### Zweites Beispiel

Wenn wir die User-Tabelle und die Movie-Tabelle kennen, so können wir diese nutzen, um fehlende Einträge in der Rating-Tabelle vorherzusagen. Das schauen wir uns  an einem   Beispiel mit der  Rating-Tabelle $R2$ und einer passenden  User-Tabelle $U2$ und  Movie-Tabelle $M2$ an:

<div style="text-align:center">
<img src="../figs/AB1_A2_b.png" width="550", class="center">
</div>


In diesem Beispiel hat Nutzer 5 die Filme 2 und 3 noch nicht gesehen.

<div id="exercise" class="alert alert-info">
    <h3><i class="fa fa-laptop" style="font-size:30px"></i> <br><br>b) Einzelne Werte von R2 aus M2 und U2 berechnen  </h3>
    Überlege zunächst, wie   die bekannten Einträge in der Rating-Tabelle $R2$ aus den Zeilen der User-Tabelle $U2$ und den Spalten der Movie-Tabelle $M2$ <strong>berechnet werden können</strong>.   
Bestimme auf gleiche Weise die fehlenden Ratings von Nutzer 5 und gib sie im Code für die <strong>None</strong> ein. Führe den Code aus.
    <hr>  <!-- Horizontale Linie -->
    <a href="../help/help2_1.ipynb"><i class="fas fa-life-ring" style="font-size:20px"></i> &nbsp;Tipp</a> <span style="margin-right: 20px;"></span>   <!-- Link zum Tipp anpassen oder Zeile löschen-->      
</div>

In [ ]:
RatingUser5Movie2 = None; 
RatingUser5Movie3 = None; 

# Hier nichts ändern!
checkPrefUser5(RatingUser5Movie2, RatingUser5Movie3)

### Drittes Beispiel


Wir schauen uns noch ein drittes Beispiel an, bei dem viele Bewertungen in der Rating-Tabelle $R3$ fehlen. Die User-Tabelle $U3$  und die Movie-Tabelle $M3$ kennen wir:

<div style="text-align:center">
<img src="../figs/AB1_A1_c.png" width="550", class="center">
</div>

<div id="exercise" class="alert alert-info">
    <h3><i class="fa fa-laptop" style="font-size:30px"></i> <br><br>c) R3 aus M3 und U3 berechnen  </h3>
    Berechne aus der gegebenen User-Tabelle $U3$ und der Movie-Tabelle $M3$ alle fehlenden Bewertungen und trage sie im folgenden Codefeld für die <strong>None</strong> ein. Führe den Code aus, um dein Ergebnis überprüfen zu lassen.
Die berechneten Bewertungen sind eine Vorhersage dafür, wie ein User einen noch nicht gesehenen Film wohl bewerten würde.
    <hr>  <!-- Horizontale Linie -->
    <a href="../help/help2_1_B.ipynb"><i class="fas fa-life-ring" style="font-size:20px"></i> &nbsp;Tipp</a> <span style="margin-right: 20px;"></span>   <!-- Link zum Tipp anpassen oder Zeile löschen-->      
</div>

In [ ]:
R3 = np.array([[None, None, 4, None], 
 [5, None, None, None], 
 [None, None, None, None],
 [None, None, None, 3]]); 

# Hier nichts ändern!
checkRatingmatrix(R3)

## 2)  Formeln für die Berechnung eines Ratings

Ziel ist es, die Vorhersage von fehlenden Bewertungen zu verallgemeinern. Wir stellen dazu eine Formel auf, mit der eine beliebige Bewertung in der Rating-Tabelle $R$ aus der User-Tabelle $U$ und der Movie-Tabelle $M$ vorhergesagt werden kann. Dazu beschreiben wird die Einträge von $R$, $U$ und $M$ durch Variablen:


<div style="text-align:left">
<img src="../figs/matrixeintrag2.png" width="160"/> 
</div>

<div style="text-align:center">
<img src="../figs/AB1_A2_c_AC.png" width="620", class="center">
</div>

**So kannst du die Tabellen lesen:**
* Die Variable $r_{34}$  entspricht dem Eintrag von $R$ in Zeile $3$ und Spalte $4$. Die Variable $r_{34}$  steht also für die Bewertung, die User 3 für Film 4 abgegeben hat (oder für ein Fragezeichen, falls die Bewertung unbekannt ist).  
* Die Variable $u_{3C}$ entspricht dem Eintrag von $U$ in Zeile 3 und Spalte $2$. Die Variable gibt also an, wie sehr User 3 die Eigenschaft **C** (=Comedy) mag.

<div id="exercise" class="alert alert-info">
    <h3><i class="fa fa-laptop" style="font-size:30px"></i> <br><br>a) Spezifische Formel bestimmen  </h3>
    Stelle eine Formel auf, mit der der Eintrag $r_{34}$ aus den Einträgen von $U$ und $M$ berechnet werden kann. Gib deine Formel für das <strong>None</strong> ein.
    <hr>  <!-- Horizontale Linie -->
    <i class="fas fa-wrench" style="font-size: 20px"></i> &nbsp;  <strong>Hinweise:</strong>  
    Du kannst   die Einträge von $U$ (<strong>u1A</strong>, <strong>u1C</strong>, ...) und  $M$ (<strong>mA1</strong>, <strong>mA2</strong>,...) bei der Eingabe deiner Formel im Code verwenden.
    <hr>  <!-- Horizontale Linie -->
    <a href="../help/help2_3.ipynb"><i class="fas fa-life-ring" style="font-size:20px"></i> &nbsp;Tipp</a> <span style="margin-right: 20px;"></span>   <!-- Link zum Tipp anpassen oder Zeile löschen-->      
</div>

In [ ]:
# Formel für den Eintrag r34
compute_r34_AC = None; 

# Hier nichts ändern!
checkCompute_r34_AC(compute_r34_AC)

Wir notieren die Berechnung der Bewertungen aus $U$ und $M$ nun noch allgemeiner, indem wir nicht mehr ausgerechnet die Eigenschaften **Action** und **Comedy** betrachten. Neben diesen beiden Genres könnten ja durchaus auch andere Genres (Romantik, Kids etc.) oder ganz andere Eigenschaften wie ein/e berühmte/r Regisseur/in relevant sein.  
Wir sprechen deswegen ab jetzt allgemein von **Eigenschaft 1** und **Eigenschaft 2**.  

<div style="text-align:center">
<img src="../figs/AB1_A2_d_R.png" width="520"/>
</div>
<div style="text-align:center">
<img src="../figs/AB1_A2_d_UM.png" width="850"/>
</div>

<div id="exercise" class="alert alert-info">
  <h3><i class="fa fa-laptop" style="font-size:36px"></i>&nbsp; <br><br> b) Beliebige Eigenschaften</h3>
    Stelle eine Formel auf, mit der der Eintrag $r_{34}$ der Rating-Tabelle $R$ aus den Einträgen von $U$ und $M$ berechnet werden kann.  
    Gib deine Formel für das <strong>None</strong> ein.
    <hr>  <!-- Horizontale Linie -->    <i class="fas fa-wrench" style="font-size: 20px"></i> &nbsp;  <strong>Hinweise:</strong>
    Du kannst   die Einträge von $U$ (<strong>u11</strong>, <strong>u12</strong>, ...) und  $M$ (<strong>m11</strong>, <strong>m12</strong>,...) bei der Eingabe deiner Formel verwenden.  
    <hr>  <!-- Horizontale Linie -->
    <a href="../help/help2_3_B.ipynb"><i class="fas fa-life-ring" style="font-size:20px"></i> &nbsp;Tipp</a> <span style="margin-right: 20px;"></span>   <!-- Link zum Tipp anpassen oder Zeile löschen-->      
</div>

In [ ]:
# Formel für den Eintrag r34
compute_r34 = None; 

# Hier nichts ändern!
checkCompute_r34(compute_r34)

## 3) Multiplikation von Matrizen

<div id="information" class="alert alert-success">
    <h2><i class="fas fa-info" style="font-size:36px"></i> &nbsp;  Hinweis</h2>
    Du Kannst diesen Workshop <strong>ohne</strong> Vorwissen zu Matrizen problemlos bearbeiten!
</div>

Bisher haben wir $R$, $U$ und $M$ stets als Tabelle bzw. als Zahlenschema aufgefasst. Dieses Zahlenschema wird in der Mathematik auch **Matrix** genannt. 
Die Rechnung aus Aufgabe 2 können wir vereinfachen bzw. **kompakter schreiben**, denn hinter deinen Formeln verbergen sich genau die Rechenregeln, die bei der Multiplikation von zwei Matrizen Anwendung finden. 

<div id="exercise" class="alert alert-info">
  <h3><i class="fa fa-laptop" style="font-size:36px"></i>&nbsp; <br><br> a) Multiplikation</h3>
    Überzeuge dich, dass das Produkt der Matrizen tatsächlich das gleiche Ergebnis liefert, wie die Formeln aus <strong>Aufgabe 2</strong>. Berechne dazu mithilfe des Computers das Produkt aus User-Tabelle (= User-Matrix) $U3$ und Movie-Tabelle (=Movie-Matrix) $M3$. Führe den folgenden Code aus.
    <div style="text-align:center">
        <img src="../figs/AB1_A1_c.png" width="550", class="center">
    </div>
</div>

In [2]:
# Hier nichts ändern! Speichern der User-Matrix
U3 = np.array([[0, 1],
              [1, 1],
              [1, 0], 
              [1, 0.5]])

# # Hier nichts ändern!Speichern der Movie-Matrix
M3 = np.array([[3, 2, 1, 1], 
              [2, 2, 4, 4]])

# Hier nichts ändern!
P = np.dot(U3, M3); print(P)

[[2. 2. 4. 4.]
 [5. 4. 5. 5.]
 [3. 2. 1. 1.]
 [4. 3. 3. 3.]]



**Hinweis:** Die Reihenfolge ist bei der Multiplikation von Matrizen  wichtig! Damit zwei Matrizen multipliziert werden können, muss gelten:   
**Anzahl Spalten der linken Matrix = Anzahl Zeilen der rechten Matrix.**

<div style="text-align:center">
<img src="../figs/matrixmultiplikationsize.png" width="500"/> 
 </div>

____
### Fazit
Wir haben die Rating-Tabelle $R$ (= Rating-Matrix) in eine User-Tabelle $U$ und eine Movie-Tabelle $M$ zerlegt. Diese beiden kleineren Tabellen (bzw. Matrizen) liefern uns Infos darüber,
* wie sehr die einzelnen User gewisse Eigenschaften mögen und
* wie sehr die einzelnen Filme diese Eigenschaften aufweisen.


**Info:** Unser bisheriges Modell wird auch **Matrix Faktorisierung** genannt. Wir zerlegen die Rating-Matrix in ein Produkt aus zwei kleineren Matrizen. Die  kleineren Matrizen können wir nutzen, um Bewertungen zu berechnen und vorherzusagen!  


# Diskussion im Plenum <img src="../figs/discussion.png" width="50"/> 
**Wir werden eure bisherigen Ergebnisse gemeinsam diskutieren!**   
Anschließend geht es weiter mit [Arbeitsblatt 3](./AB3-SuS.ipynb).
_____


<div id="exercise" class="alert alert-info">
  <h3><i class="fa fa-laptop" style="font-size:36px"></i>&nbsp; <br><br> Zusatzaufgabe</h3>
    Welches mathematische Konzept verbirgt sich hinter der Berechnung eines Ratings aus den Zeilen der User-Matrix und den Spalten der Movie-Matrix? Wie lässt sich anschaulich erklären, wann diese Berechnung ein größeres und wann ein kleineres Rating liefert? Deine Ideen kannst du auf diesem <a href="./Zusatzmaterial/AB_SKP-SuS.ipynb">&nbsp;Zusatzblatt</a> überprüfen.
</div>

<div id="information" class="alert alert-success">
    <h2><i class="fas fa-info" style="font-size:36px"></i> &nbsp;  Zusatzinfo</h2>
    Wenn du mehr zu Matrizen und deren Rechenregeln erfahren möchtest, öffne dieses <a href="../help/info_Matrizen.ipynb">&nbsp;Infoblatt<a>.
</div>

 ___
<a rel=“license” href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a> Dieses Werk ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International Lizenz</a>

Autorin: Sarah Schönbrodt